name: Cache NCSC-FI RSS to branch feed-cache

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch NCSC-FI RSS
        run: |
          node -v
          npm -v
          node scripts/fetch_ncsc_feed.mjs

      - name: Publish to feed-cache branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: feed-cache
          folder: cache
          clean: true
          single-commit: true
          commit-message: "chore: update NCSC-FI RSS cache [skip ci]"

