name: Cache NCSC-FI RSS to branch feed-cache

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch NCSC-FI RSS
        run: |
          node -v
          npm -v
          node scripts/fetch_ncsc_feed.mjs

      - name: Publish to feed-cache branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # Create or switch to feed-cache branch
          git checkout -B feed-cache
          git add ncsc-rss.json
          git commit -m "chore: update NCSC-FI RSS cache [skip ci]" || echo "No changes to commit"
          git push origin feed-cache

